#!/usr/bin/env python3
"""Cut the Phasor's tone stage out of appletini-one's mockingboard.sv into a
stand-alone module, verbatim, for tone/tone_rtl.cpp.

usage: extract_tone.py MOCKINGBOARD_SV OUT_SV

What is copied unchanged: the functions the stage calls, the declarations
of the tone_* registers, and the whole `begin : final_audio_mix` block of
the mixer's always_ff. One edit: the block's base selection (PSG mix by
mode + speech) becomes mix_speech(16'sd0, in_x), the speech alone, which is
what the block computes when the PSGs are silent (mix4_to_pcm(0) and
mix2_to_pcm(0) are 0). The reset branch zeroes the same registers the RTL's
`if (!rstn || !card_enabled)` branch does (checked: every tone_* register
and audio_l/audio_r, nothing else of the stage).
"""
import re, sys

src, out = sys.argv[1], sys.argv[2]
text = open(src).read()
lines = text.split('\n')

FUNCS = ['sat_add16', 'mix_speech', 'clamp_audio_control', 'pcm_to_tone_fp', 'tone_fp_to_pcm',
         'audio_control_adjust', 'warmth_treble_adjust', 'sat16_from21', 'warm_shape_from21']
funcs = []
for name in FUNCS:
    m = re.search(r'^function automatic [^\n]*\b' + name + r'\(.*?^endfunction\n', text, re.S | re.M)
    if not m:
        sys.exit(f'function {name} not found')
    funcs.append(m.group(0))

decls = [l for l in lines if re.match(r'^logic signed \[\d+:0\] tone_\w+;$', l)]
regs = [re.match(r'^logic signed \[\d+:0\] (tone_\w+);$', l).group(1) for l in decls]
if len(regs) < 30:
    sys.exit('tone register declarations not found')

# The RTL's reset list for these registers.
resets = set(re.findall(r'^\s+(tone_\w+|audio_l|audio_r) <= \'0;$', text, re.M))
missing = [r for r in regs + ['audio_l', 'audio_r'] if r not in resets]
if missing:
    sys.exit(f'not reset in the RTL as assumed: {missing}')

# The final_audio_mix block, by begin/end nesting.
start = next(i for i, l in enumerate(lines) if 'begin : final_audio_mix' in l)
depth, end = 0, None
for i in range(start, len(lines)):
    toks = re.findall(r'\bbegin\b|\bend\b', lines[i])
    for t in toks:
        depth += 1 if t == 'begin' else -1
    if depth == 0:
        end = i
        break
block = lines[start:end + 1]
# Replace the base selection: from "if (phasor_native) begin" to the line
# before "tone_base_l_q <= base_l_next;".
a = next(i for i, l in enumerate(block) if l.strip() == 'if (phasor_native) begin')
b = next(i for i, l in enumerate(block) if l.strip() == 'tone_base_l_q <= base_l_next;')
sel = block[a:b]
if not any('ssi0_audio' in l for l in sel) or not any('ssi1_audio' in l for l in sel):
    sys.exit('base selection not as expected')
ind = re.match(r'\s*', block[a]).group(0)
block = block[:a] + [
    ind + '// tone/extract_tone.py: the PSG mix is 0 (muted), so the base is the speech',
    ind + "base_l_next = mix_speech(16'sd0, in_l);",
    ind + "base_r_next = mix_speech(16'sd0, in_r);",
    ''] + block[b:]

o = []
o.append('// Generated by tone/extract_tone.py from ' + src + '; do not edit.')
o.append('`timescale 1ns / 1ps')
o.append('module tone_stage (')
o.append('    input  logic clk,')
o.append('    input  logic rstn,')
o.append('    input  logic [31:0] audio_control,')
o.append('    input  logic signed [15:0] in_l,   // ssi0_audio')
o.append('    input  logic signed [15:0] in_r,   // ssi1_audio')
o.append('    output logic signed [15:0] audio_l,')
o.append('    output logic signed [15:0] audio_r')
o.append(');')
o += decls
o.append('')
o += funcs
o.append('always_ff @(posedge clk) begin')
o.append('    if (!rstn) begin')
for r in regs + ['audio_l', 'audio_r']:
    o.append(f"        {r} <= '0;")
o.append('    end else begin')
o += block
o.append('    end')
o.append('end')
o.append('endmodule')
open(out, 'w').write('\n'.join(o) + '\n')
print(f'{out}: {len(funcs)} functions, {len(regs)} registers, block lines {start + 1}-{end + 1} of {src}')
